version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    env_file: ./api-gateway/.env
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://guest:guest@localhost:8090
  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    env_file: ./auth-service/.env
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://guest:guest@localhost:8090
  user-service:
    build: ./user-service
    ports:
      - "3002:3002"
    env_file: ./user-service/.env
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://guest:guest@localhost:8090
  ticket-service:
    build: ./ticket-service
    ports:
      - "3003:3003"
    env_file: ./ticket-service/.env
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://guest:guest@localhost:8090
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "8090:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
